kpu/kenlm

- CMakeLists.txt
- lm/CMakeLists.txt
- lm/builder/CMakeLists.txt
- lm/filter/CMakeLists.txt
- lm/interpolate/CMakeLists.txt
- util/CMakeLists.txt
I've done the following to cleanup the build process on MSVC (Visual Studio 2013): 
* Suppress C4716
* Do not include pthread if on Windows/MSVC
* Use /MT (statically linked MSVCRT) when FORCE_STATIC is enabled
* Add additional Boost libraries as required for the build
* Using CMake module-defined parameters for compression libraries (ZLIB, BZIP2, LZMA)
We were targeting only a subset of the tools this project builds, so this change will probably not fix all Windows build issues across all targets. It resulted in a successful build of lmplz and its dependencies.
> CMake Windows Build Cleanup 

- lm/interpolate/tune_instances_test.cc
Hi!
I have a compilation error when compiling the "tune_instances_test" unit test, only when using g++ 6.1.1 (it works with older g++ versions).
`
In file included from /usr/include/boost/test/test_tools.hpp:45:0,
from /usr/include/boost/test/unit_test.hpp:18,
from /home/vincent/dev/kenlm/lm/interpolate/tune_instances_test.cc:11:
/home/vincent/dev/kenlm/lm/interpolate/tune_instances_test.cc: In member function ‘void lm::interpolate::{anonymous}::Toy::test_method()’:
/home/vincent/dev/kenlm/lm/interpolate/tune_instances_test.cc:55:39: error: ‘isnan’ was not declared in this scope
BOOST_CHECK(!isnan(ln_unigrams(1, 0)));
`
It seems that, as isnan() is only defined in C++11, the compiler is not able to find the required function in the "cmath" header.
You can fix the problem by including the …
> Fix compilation error (isnan) with g++ 6.1.1

- python/example.py
There is no `Model` in python interface:
```
>>> model = kenlm.Model(LM)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Model'
```
Check the python interface `help(kenlm)` and we obtain:
```
Help on module kenlm:
NAME
kenlm
FILE
/workspace/jialinwu/anaconda2/lib/python2.7/site-packages/kenlm.so
CLASSES
__builtin__.object
LanguageModel
class LanguageModel(__builtin__.object)
|  Methods defined here:
|
|  __contains__(...)
|      x.__contains__(y) <==> y in x
|
|  __init__(...)
|      x.__init__(...) initializes x; see help(type(x)) for signature
|
|  __reduce__(...)
|
|  __repr__(...)
|      x.__repr__() <==> repr(x)
|
|  full_scores(...)
|
|  score(...)
|
| …
```
> Rename Model to LanguageModel

- BUILDING
Inform folks compiling on OSX that dependencies can be managed with brew; provide instructions to which packages will resolve dependencies.  
Tested on OSX Mojave (10.14.1)
> update BUILDING with OSX instructions

- util/file.cc
The C header files for musl (used in e.g. Alpine Linux) define `_GNU_SOURCE` but not `__GLIBC_PREREQ`, making the line
```
#if __GLIBC_PREREQ(2,17)
```
a syntax error:
```
util/file.cc:544:19: error: missing binary operator before token "("
#if __GLIBC_PREREQ(2,17)
^
error: command 'gcc' failed with exit status 1
```
cf:
https://github.com/leo-yuriev/ReOpenLDAP/issues/123
http://www.openwall.com/lists/musl/2012/10/20/10
This wraps the use of `__GLIBC_PREREQ` in a `defined()` guard.
> Guard against missing __GNUC_PREREQ

- lm/build_binary_main.cc
For DeepSpeech we ship a separate data structure for the vocabulary alongside the LM, so we'd like to avoid packaging the same data twice.
> Add flag to build_binary to disable inclusion of vocabulary

- BUILDING
- README.md
List the exact Ubuntu packages that contain the build dependencies.
Tested on Ubuntu 18.04 LTS for desktop and Raspian stretch on Rasp Pi.
> Document Ubuntu build dependencies

- util/usage.cc
This patch makes kenlm builds on freebsd.
FreeBSD does not have mach/task.h or mach/mach.h. Neither does it have mach_task_self() etc.
> Fix build on FreeBSD

- lm/quantize.hh
- util/bit_packing.hh
1. BitPackShift() doesn't return the right value on big endian for
{Read,Write}Int25. Consecutive25 would just fail on big endian.
The fix is to round it to 32 instead 64.
2. Using a WriteInt57 and Two ReadInt25 to read the combined integer value
won't simply work on big endian. The fix just simply replace the
WriteInt57 with two ReadInt25 for MiddlePointer.
> Fix bit packing and quantize on big endian.

- lm/quantize.hh
The bit shifted need to be the length of the one on lower bits.
> Fix Quantize bit packing on big endian.

- util/CMakeLists.txt
- util/usage.cc
release thus proposing to detect at "configure" time its availability
whether it comes from libc or librt instead.
> Second mac os change proposal. clock_gettime is supported since 10.12

- CMakeLists.txt
- cmake/kenlmConfig.cmake.in
- lm/CMakeLists.txt
- lm/builder/CMakeLists.txt
- util/CMakeLists.txt
Creates CMake config file for KenLM i.e.
https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/How-to-create-a-ProjectConfig.cmake-file.
This change creates one and lets KenLM interact with modern CMake
projects without a ton of Findkenlm.cmake cruft (right now projects need
this file to interoperate with installed KenLM libs, and need to themselves
install it and pass it to their dependent projects, which is a lot of extra work).
Other improvements include:
- Remove duplicative linking of `${Boost_LIBRARIES}` and instead link
to kenlm_util once then transitively to other targets
- Do the same for Threads::Threads
- Both of the above libraries are handled for transitive linking via
CMake's `find_dependency(...)` in the genreated `kenlmConfig.cmake`
- Wrap libraries in …
> Modernize CMake install

- CMakeLists.txt
- cmake/kenlmConfig.cmake.in
- lm/CMakeLists.txt
- lm/builder/CMakeLists.txt
- lm/filter/CMakeLists.txt
- lm/interpolate/CMakeLists.txt
- util/CMakeLists.txt
Fixes https://github.com/kpu/kenlm/issues/336.
- Fix CMake going back to 3.1 -- (https://cmake.org/Bug/view.php?id=14444)
- Moves `install` calls back to the directories where their librari
targets are created
- Make non-transitive dependencies private (compression libs, etc) rather
than using generator expressions
- Install auxiliary libraries (besides kenlm/kenlm_util)
- Gate compression lib deps in kenlmConfig by whether they were found at
compile time
> CMake improvements/fixes for old versions

- .gitignore
- setup.py
Building a dylib on macOS means that the installed KenLM artifact can be used either by Python directly via `import python` or consumed by C++ libraries that want to have KenLM as a runtime dependency.
With both of these approaches, Python users can `pip install git+https://github.com/kpu/kenlm` and get a library that can be universally consumed.
Since Linux allows for linking against `.so` ELF objects, this isn't needed on Linux. Windows is similar.
> Always build a dylib when building Python bindings on macOS

- setup.py
For whatever reason, when KenLM is built from `pip` (e.g. `pip install git+https://github.com/kpu/kenlm.git`), `/usr/local/include` isn't getting properly propagated on some macOS systems, and the resulting build can't find `lzma.h`. The test compilation with that header works when specifically passed with `-include lzma.h`, but fails when built by the `setuptools` `Extension`.
Failure example here: https://app.circleci.com/pipelines/github/flashlight/text/283/workflows/f4d5ff8f-2201-401b-a8d7-bf207fd7e64f/jobs/2492
> Manually set include paths on macOS to find LZMA

- CMakeLists.txt
- lm/CMakeLists.txt
- pyproject.toml
- python/BuildStandalone.cmake
- setup.py
Augments the Python build to also ship C++ library builds of KenLM that are dynamically usable by other C++ libs. Specifically, `pip install .` in the repo (or `pip install git+https://github.com/kpu/kenlm`, as it'll likely be most often used) now installs:
- `kenlm.cpython-[platform].{so,pyd}` (as before) -- openable by Python
- `libkenlm.{so,dll,lib}` [new] -- not loadable by Python but usable by C++ libraries.
In particular, this PR:
- Moves the `KENLM_MAX_ORDER` CMake definition to the beginning of the build
- Adds `BuildStandalone.cmake`, enabled by `BUILD_PYTHON_STANDALONE`, which builds `libkenlm` as a shared lib containing symbols from all project sources
- Removes forcing building a `-dynamiclib` on macOS and let CMake handle this. MSVC will build a `pyd` (special DLL) anyways on …
> Add standalone lib build with Python install

- README.md
- setup.py
Fixes the max order issue outlined in https://github.com/kpu/kenlm/pull/417 -- PEP 517 performs isolated builds by default when `pyproject.toml` is present, and isolated builds are the future of Python/pip. `--install-option` is ignored in isolated builds, and when used, it also prevents binary and wheel caching (see https://github.com/pypa/pip/issues/11451), which dramatically slows down the build.
> Swap --max-order to use an environment variable given PEP 517 and 518

- util/string_piece_hash.hh
Hello, I'm a member of Microsoft VCPKG, when I built this port in an internal version of Visual Studio, it failed with following errors:
```
D:\buildtrees\kenlm\src\2b1d91de6b-bf52422165.clean\util/string_piece_hash.hh(23): error C2039: 'unary_function': is not a member of 'std'
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\typeindex(25): note: see declaration of 'std'
D:\buildtrees\kenlm\src\2b1d91de6b-bf52422165.clean\util/string_piece_hash.hh(23): error C2504: 'unary_function': base class undefined
D:\buildtrees\kenlm\src\2b1d91de6b-bf52422165.clean\util/string_piece_hash.hh(23): error C2143: syntax error: missing ',' before '<'
```
The reason is new STL change, need include `<functional>` to fix them.
> Include functional to fix error C2039 and C2504

- lm/trie_sort.cc
Allows LLVM to succeed with `-Wunused-but-set-variable`
> Remove unused variable from trie_sort.cc

- CMakeLists.txt
- pyproject.toml
- python/BuildStandalone.cmake
This pull request includes updates to the minimum required CMake version across various files to ensure compatibility with newer features. The most important changes are:
Updates to CMake version requirements:
* [`CMakeLists.txt`](diffhunk://#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL1-R1): Updated the minimum CMake version from 3.1 to 3.10.
* [`python/BuildStandalone.cmake`](diffhunk://#diff-e095bc233e8bc7c9f9a25f31738d9718433d1440389c8dffdb1a68a9d8003fe2L1-R1): Updated the minimum CMake version from 3.1 to 3.10.
Dependency updates:
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L2-R2): Modified the required CMake version to be at least 3.10.
> Fix build with cmake 4.0
